//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TES.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TESDBEntities : DbContext
    {
        public TESDBEntities()
            : base("name=TESDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tender> Tender { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<References> References { get; set; }
        public virtual DbSet<Approved> Approved { get; set; }
        public virtual DbSet<Approved_View> Approved_View { get; set; }
        public virtual DbSet<References_View> References_View { get; set; }
    
        public virtual int usp_Tender_Control()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Tender_Control");
        }
    }
}
