//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class References
    {
        public int Id { get; set; }
        public Nullable<int> TenderId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string Note { get; set; }
        public Nullable<float> Money { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
